package com.stratio.decision.commons;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PocData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String fieldString;
   private Integer fieldInteger;

   public PocData()
   {
   }
   
    public PocData(String fieldString, Integer fieldInteger)
   {
       this.fieldString = fieldString;
       this.fieldInteger = fieldInteger;
   }

   public String getFieldString()
   {
      return this.fieldString;
   }

   public void setFieldString(String fieldString)
   {
      this.fieldString = fieldString;
   }
   
   public Integer getFieldInteger()
   {
      return this.fieldInteger;
   }

   public void setFieldInteger(Integer fieldInteger)
   {
      this.fieldInteger = fieldInteger;
   }

  

}