package com.stratio.decision.orders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LineaCompra implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer id;
   private java.lang.Integer cantidad;
   private java.lang.Integer precio;

   public LineaCompra()
   {
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public java.lang.Integer getCantidad()
   {
      return this.cantidad;
   }

   public void setCantidad(java.lang.Integer cantidad)
   {
      this.cantidad = cantidad;
   }

   public java.lang.Integer getPrecio()
   {
      return this.precio;
   }

   public void setPrecio(java.lang.Integer precio)
   {
      this.precio = precio;
   }

   public LineaCompra(java.lang.Integer id, java.lang.Integer cantidad,
         java.lang.Integer precio)
   {
      this.id = id;
      this.cantidad = cantidad;
      this.precio = precio;
   }

}