package com.stratio.decision.demo_orders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Action implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.Integer idCliente;
   private java.lang.String action;
   private java.lang.String typeFraud;

   public Action()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.Integer getIdCliente()
   {
      return this.idCliente;
   }

   public void setIdCliente(java.lang.Integer idCliente)
   {
      this.idCliente = idCliente;
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public java.lang.String getTypeFraud()
   {
      return this.typeFraud;
   }

   public void setTypeFraud(java.lang.String typeFraud)
   {
      this.typeFraud = typeFraud;
   }

   public Action(java.lang.String id, java.lang.Integer idCliente,
         java.lang.String action, java.lang.String typeFraud)
   {
      this.id = id;
      this.idCliente = idCliente;
      this.action = action;
      this.typeFraud = typeFraud;
   }

}